[USVISA]
; Account and current appointment info from https://ais.usvisa-info.com
USERNAME = anjalijojimathew@gmail.com
PASSWORD = AJMajce18-22$
SCHEDULE_ID = 40044976
MY_SCHEDULE_DATE = 2025-06-03
; Canada - Montreal
COUNTRY_CODE = en-ca
; Montreal
FACILITY_ID = 12

[CHROMEDRIVER]
; Details for the script to control Chrome
LOCAL_USE = True
; Optional: HUB_ADDRESS is mandatory only when LOCAL_USE = False
HUB_ADDRESS = http://localhost:9515/wd/hub

[PUSHOVER]
; Get push notifications via https://pushover.net/ (optional)
PUSH_TOKEN = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PUSH_USER = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[SENDGRID]
; Get email notifications via https://sendgrid.com/ (optional)
SENDGRID_API_KEY = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
